
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBm-S5A","is_bot":false,"login":"alicezhong1","name":""},"headRefName":"Alice-ZipCode-Controller","number":27,"title":"Alice zip code controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-4/pull/27"},{"author":{"id":"MDQ6VXNlcjc2NDUzODIw","is_bot":false,"login":"EricM5","name":"Eric Marzouk"},"headRefName":"Eric-University-Controller","number":26,"title":"Add University Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-4/pull/26"},{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"Benjamin-LocationService-Controller","number":22,"title":"Benjamin Location Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-4/pull/22"}]
