
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-7pm-4
owner: ucsb-cs156-f23
repo_name: team01-f23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQyNDg2NTk1","is_bot":false,"login":"Bennyyyyy","name":"Benny Conte"},"headRefName":"Benjamin-LocationService","number":21,"title":"Add Location Service and Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-4/pull/21"},{"author":{"id":"U_kgDOBXhX9g","is_bot":false,"login":"apzhou0","name":""},"headRefName":"Audrey-Joke","number":20,"title":"Add Joke Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-4/pull/20"},{"author":{"id":"MDQ6VXNlcjQxMzg3MDAz","is_bot":false,"login":"audoreven","name":""},"headRefName":"Audrey-PublicHoliday-Controller","number":19,"title":"Add Public Holiday Service and Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-7pm-4/pull/19"}]
